name: EVM Tests Action

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'evm') && contains(github.event.pull_request.labels.*.name, 'smart-contract')
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./projects/evm

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: false    
    
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        run: pnpm install

      - run: pnpm install
        working-directory: projects/server
       
      - name: Build
        run: pnpm build
          
      - name: Run tests
        run: pnpm test
