name: lint-actions
on: [ push ]
jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: >
          npm install 
          eslint
          prettier
          @typescript-eslint/eslint-plugin 
          @typescript-eslint/parser
          eslint-config-prettier 
          eslint-config-standard 
          eslint-plugin-import 
          eslint-plugin-node
          eslint-plugin-prettier 
          eslint-plugin-promise
      - run: npx eslint "test/**/*.ts"
